### ISSUE TITLE
Home Page and Other Routes Shows a Blank Screen

### ISSUE THREAD

**Issue by nessun-dorma** [PreMiD/Documentation#917]
I recently developed an interest towards PreMiD and I wanted to create a presence for Frontend Masters but the Docs aren't accessible so I couldn't proceed
![image](https://user-images.githubusercontent.com/96528048/159129976-11c3f086-646a-404a-9dae-5e5556453947.png)
![image](https://user-images.githubusercontent.com/96528048/159129994-8d3740bc-d70b-4847-b205-a0c92cdb7dfd.png)

**Comment by EncryptedDev** [comment]
Should have been fixed now
